### ISSUE TITLE
Couchbase::Model#update_attributes doesn't save the record

### ISSUE THREAD

**Issue by archit** [couchbase/couchbase-ruby-model#27]
[ActiveRecord::Base#update_attribute](https://github.com/rails/rails/blob/748cc75705af6db3cca5e670c80e570fdb8c18c4/activerecord/lib/active_record/persistence.rb#L227) also saves the record. `Couchbase::Model#update_attributes` doesn't. 

Seeing how this library is supposed to mimic the behavior of ActiveRecord::Base, this seems like a bug. I'll try and cook up a fix in a bit.

**Comment by avsej** [comment]
fixed by #28
